# .github/dependabot.yml
# Configuration for Dependabot to keep dependencies up-to-date.

version: 2
updates:
  # Enable weekly updates for pip (Python)
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add labels to PRs
    labels:
      - "python"
      - "dependencies"

  # Enable weekly updates for npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add labels to PRs
    labels:
      - "javascript"
      - "dependencies"
